version: '3.9'
services:
    samwaf:
        image: samwaf/samwaf
        volumes:
            - './ssl:/app/ssl'
            - './logs:/app/logs'
            - './data:/app/data'
            - './conf:/app/conf'
        ports:
            - '6443:443'
            - '6080:80'
            - '26666:26666'
        container_name: samwaf-instance

