services:
  minio1:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - m1_data:/data
    networks:
      - pub-network
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

  minio2:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - m2_data:/data
    networks:
      - pub-network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

  minio3:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    volumes:
      - m3_data:/data
    networks:
      - pub-network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    command: server http://minio{1...3}/data --console-address ":9001"

volumes:
  m1_data:
  m2_data:
  m3_data:

networks:  # 加入公共网络
  pub-network:
      external: true
