version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: [ "--max_connections=1000" ]
    ports:
      - "3307:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/log:/var/log/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
    environment:
       - MYSQL_ROOT_PASSWORD=123456
       - MYSQL_ALLOW_EMPTY_PASSWORD=no
       - MYSQL_USER=yourname
       - MYSQL_PASS=password
    networks:
      - localhost-network
    restart: always

volumes:
  mysql:
  mysql_config:

networks:
  localhost-network:
    name: localhost-network-1
