services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
      - ./font/:/usr/share/fonts/truetype/dejavu/
    environment:
      - MYSQL_ROOT_PASSWORD=next_cloud_root_passwd
      - MYSQL_PASSWORD=next_cloud_passwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - next_cloud_network
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=next_cloud_passwd
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - next_cloud_network
volumes:
  nextcloud:
  db:
networks:
    next_cloud_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.44.0.0/24