version: "3"
services:
  umami:
      image: ghcr.io/umami-software/umami:postgresql-latest
      ports:
        - "3000:3000"
      environment:
        DATABASE_URL: postgresql://umami:umami@db:5432/umami
      depends_on:
        - db
# todo 配置未完成
  db:
    image: postgres:latest
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./db.conf:/etc/postgresql.conf
