version: '3.8'

services:
  xunlei:
    image: cnk3x/xunlei:latest
    container_name: xunlei
    ports:
      - "2345:2345"
    volumes:
      - ./volume/data:/xunlei/data        # 配置目录
      - ./volume/media:/xunlei/downloads  # 下载目录
    environment:
      XL_DASHBOARD_USERNAME: "admin"     # 替换为你的用户名
      XL_DASHBOARD_PASSWORD: "1q@W3e4r5t"       # 替换为你的密码
    restart: always
    privileged: true
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
