version: '2.2'
services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs:/logs
    command: redis-server /usr/local/etc/redis/redis.conf
