version: '3.9'
services:
    jumpserver:
        image: jumpserver/jms_all:latest
        environment:
            - SECRET_KEY=dzyzZrDWAeZF5QDgKBl8uqs8H5dOZVlJmTg6R0dEsojhum7OMO
            - BOOTSTRAP_TOKEN=xezlBxLpNG51LSBi
            - DB_ENGINE=mysql
            - DB_HOST=192.168.0.126
            - DB_PORT=3307
            - DB_USER=root
            - DB_PASSWORD="123456"
            - DB_NAME=jumpserver
            - REDIS_HOST=192.168.0.126
            - REDIS_PORT=6380
            - REDIS_PASSWORD="123456"
        ports:
            - 2222:2222
            - 80:80
        volumes:
            - ./data/jumpserver:/opt/jumpserver/data/media
        restart: always
        hostname: jumpserver
        container_name: jumpserver

# 终端生成SECRET_KEY随机秘钥：
# if [ "$SECRET_KEY" = "" ]; then SECRET_KEY=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 50`; echo "SECRET_KEY=$SECRET_KEY" >> ~/.bashrc; echo $SECRET_KEY; else echo $SECRET_KEY; fi
# 终端生成TOKEN随机秘钥：
# if [ "$BOOTSTRAP_TOKEN" = "" ]; then BOOTSTRAP_TOKEN=`cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 16`; echo "BOOTSTRAP_TOKEN=$BOOTSTRAP_TOKEN" >> ~/.bashrc; echo $BOOTSTRAP_TOKEN; else echo $BOOTSTRAP_TOKEN; fi