version: '3.8'

services:
  univer-frontend:
      image: univer-acr-registry.cn-shenzhen.cr.aliyuncs.com/release/univer-collaboration-lite:latest
      container_name: univer-collaboration-lite
      networks:
        - univer-prod
      ports:
        - "56789:3010"
      restart: unless-stopped

networks:
  univer-prod:
      driver: bridge
